server:
  port: 8080

spring:
  application:
    name: immopulse-api

  datasource:
    postgres:
      url: jdbc:postgresql://localhost:5432/default_database
      username: username
      password: password
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 10 
    clickhouse:
      url: jdbc:clickhouse://localhost:8123/default?compress=0&socket_timeout=180000
      username: username
      password: password
      driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
      hikari:
        maximum-pool-size: 30
        connection-timeout: 180000 

  jpa:
    show-sql: true 
    hibernate:
      ddl-auto: update 

logging:
  level:
    org:
      springframework:
        web: DEBUG
        cache: TRACE

springdoc:
  swagger-ui:
    path: /docs

management:
  tracing:
    sampling:
      probability: '1.0'
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs
  observations:
    annotations:
      enabled: true
